services:
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/pihub/matter-server/data:/data
      - /run/dbus:/run/dbus:ro
    command: ["--storage-path", "/data", "--primary-interface", "wlan0", "--bluetooth-adapter", "0", "--log-level", "verbose", "--paa-root-cert-dir", "/data/credentials"]
